Homework 3
Kuzeikind/NikolaiKuzeikin pull request #3
Opened 2021-10-29 18:37 UTC by Kuzeikind

Test refactored and passing.

2021-11-02 23:16 UTC, akulebyakin requested changes
From my point of view pages hierarchy is way too complicated for the application (I hope this diagram I created is correct)
![image](https://user-images.githubusercontent.com/46869924/139964317-c9abe1d0-ed2f-4dc2-91df-a077a968655c.png)

- CheckBoxSection and RadioSection should't be inherited from AbstractMenu
- For pages there can be only one-layer of inheritance. I'd be much easier to support and extend

![image](https://user-images.githubusercontent.com/46869924/139964716-34d68047-b6ea-405c-ae6b-de56198e250b.png)

Please review the comments.

2021-11-02 23:16 UTC, akulebyakin commented on src/main/java/com/epam/tc/hw3/components/leftside/LeftSideMenu.java
> +    protected ServicesMenu servicesMenu;
Why not private?

2021-11-03 12:16 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/AbstractPage.java
> +public class AbstractPage {
Made the class abstract. Was a mistake.

2021-11-03 12:17 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/BasePage.java
> +               .findAny();
Changed to list.isEmpty().

2021-11-03 12:18 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/driverutil/DriverServiceImpl.java
> +        WebDriver driver = new ChromeDriver();
Reworked the class to provide different browsers as specified in the properties.

2021-11-03 12:19 UTC, Kuzeikind commented on src/test/java/com/epam/tc/hw3/BaseTest.java
> +    }
Rewrote methods to exclude multiple BeforeMethod's and BeforeClass'es.

2021-11-03 12:20 UTC, Kuzeikind commented on src/test/java/com/epam/tc/hw3/BaseTest.java
> +import com.epam.tc.hw2.util.TestUtil;
Corrected the mistake.

2021-11-03 13:19 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/AbstractPage.java
> +public class AbstractPage {
> Made the class abstract. Was a mistake.

Removed the class totally.

2021-11-03 13:20 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/BasePage.java
> +public class BasePage extends AbstractPage {
Reworked the page classes hierarchy, reducing the depth of inheritance.

2021-11-03 13:21 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/HomePage.java
> +    }
Shouldn't be an issue with the new pages hierarchy.

2021-11-03 13:22 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/components/BenefitsSection.java
> +        PageFactory.initElements(driver, this);
Disagree. Each component has its own unique web elements and we need to initialise them in each class separately.

2021-11-03 13:24 UTC, Kuzeikind commented on src/test/java/com/epam/tc/hw3/BaseTest.java
> +    }
HomePage is now the page loaded for the URL. BasePage is now the abstract superclass for all pages.

2021-11-03 14:45 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw3/components/leftside/LeftSideMenu.java
> +    protected ServicesMenu servicesMenu;
Changed to private.

2021-11-03 18:28 UTC, akulebyakin approved these changes
Approved
Great job!

2021-11-03 19:28 UTC, merged