Homework 4
Kuzeikind/NikolaiKuzeikin pull request #4
Opened 2021-11-04 11:25 UTC by Kuzeikind

Test refactored with the steps pattern.

2021-11-08 14:17 UTC, akulebyakin requested changes
Review comments please

2021-11-09 13:58 UTC, Kuzeikind commented on src/test/java/com/epam/tc/hw4/steps/HomePageSteps.java
> +public class HomePageSteps {
Fixed the issue.

2021-11-09 13:58 UTC, Kuzeikind commented on src/test/java/com/epam/tc/hw4/steps/DifferentElementsPageSteps.java
> +    }
Added proper description to the tests.

2021-11-10 09:11 UTC, akulebyakin approved these changes
Approved. Good job!

2021-11-10 10:56 UTC, merged