Homework jdi
Kuzeikind/NikolaiKuzeikin pull request #7
Opened 2021-11-19 08:51 UTC by Kuzeikind

Homework 7 done.

2021-11-25 18:05 UTC, cold-flame requested changes

2021-11-28 08:30 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw7/JdiTestingSite.java
> +    @UI(HeaderLocators.HEADER_MENU_ITEM)
Moved fields to HomePage.

2021-11-28 08:30 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw7/locators/MetalsAndColorsPageLocators.java
> +public class MetalsAndColorsPageLocators {
Deleted this class.

2021-11-28 08:30 UTC, Kuzeikind commented on src/test/java/com/epam/tc/hw7/InitTest.java
> +    @BeforeClass(alwaysRun = true)
Deleted this class.

2021-11-28 08:30 UTC, Kuzeikind commented on src/main/java/com/epam/tc/hw7/locators/HeaderLocators.java
> +public class HeaderLocators {
Deleted this class.

2021-11-30 16:08 UTC, cold-flame approved these changes

2021-12-01 11:26 UTC, merged